[package]
name = "shakmaty"
version = "0.7.2" # remember to update html_root_url
description = "A library for chess move generation"
repository = "https://github.com/niklasf/shakmaty"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games", "parsing"]
keywords = ["chess"]
build = "src/build.rs"

[[bench]]
name = "benches"
harness = false

[dependencies]
bitflags = "1.0"
option-filter = "1.0"
btoi = "0.3"
smallvec = "0.6"

[build-dependencies]
version_check = "0.1"

[dev-dependencies]
bencher = "0.1"

[badges]
travis-ci = { repository = "niklasf/shakmaty", branch = "master" }
